/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package bancodados;

import java.beans.PropertyVetoException; // Importa exceção usada para manipulação de janelas internas
import java.sql.Connection; // Interface de conexão com o banco de dados
import java.sql.PreparedStatement; // Usado para executar comandos SQL parametrizados
import java.sql.ResultSet; // Representa o resultado de uma consulta SQL
import java.sql.SQLException; // Exceção para erros SQL
import java.util.logging.Level; // Nível de logging
import java.util.logging.Logger; // Logger para registrar mensagens
import javax.swing.JOptionPane; // Caixa de diálogo para mensagens
import javax.swing.table.DefaultTableCellRenderer; // (Importação não usada aqui)
import javax.swing.table.DefaultTableModel; // Modelo de dados para JTable

/**
 *
 * @author Rafael55957146
 */
public final class TelaExibicao extends javax.swing.JInternalFrame {

    String situacao;
    
    /**
     * Creates new form TelaPrincipal
     * @throws java.beans.PropertyVetoException
     */
    public TelaExibicao() throws PropertyVetoException {
        initComponents();
        
        tfCodigo.setEnabled(false);
        setMaximum(true);
        atualizarTabela(); 
        
    }
    
    public void atualizarTabela() {
    
        try {
            Connection con =  ConexaoMysql.conexaoBanco();
            String sql = "SELECT * FROM produto ORDER BY id_produto";
            PreparedStatement stmt = con.prepareCall(sql);
            ResultSet rs = stmt.executeQuery();

            DefaultTableModel tabelaResultado = (DefaultTableModel) tabela.getModel();
            tabelaResultado.setNumRows(0);
            
            while(rs.next()) {
            
                Object[] dados = {
                rs.getString("id_produto"),
                rs.getString("denominacao"), 
                rs.getString("quantidade_estoque"),
                rs.getString("preco"), 
                rs.getString("situacao")
                  
                };
                tabelaResultado.addRow(dados);
            }
            
            stmt.close();
            con.close();
            rs.close();
            
        } catch (SQLException ex) {
            Logger.getLogger(TelaExibicao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void resetarDados() {
    tfCodigo.setText(null);
    tfDenominacao.setText(null);
    tfQuantidadeEstoque.setText(null);
    tfPreco.setText(null);
    rbSituacao.clearSelection();
    
    
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbSituacao = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        painel2 = new javax.swing.JDesktopPane();
        tfPreco = new javax.swing.JTextField();
        lbCodigo = new javax.swing.JLabel();
        lbDenominacao = new javax.swing.JLabel();
        lbQuantidadeEstoque = new javax.swing.JLabel();
        lbPreco = new javax.swing.JLabel();
        lbSituacao = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        tfDenominacao = new javax.swing.JTextField();
        tfQuantidadeEstoque = new javax.swing.JTextField();
        rbInativo = new javax.swing.JRadioButton();
        rbAtivo = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        btnCadastrar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        tfPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPrecoActionPerformed(evt);
            }
        });

        lbCodigo.setText("Código");

        lbDenominacao.setText("Denominação");

        lbQuantidadeEstoque.setText("Quantidade Estoque");

        lbPreco.setText("Preço");

        lbSituacao.setText("Situação:");

        tfCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCodigoActionPerformed(evt);
            }
        });

        tfDenominacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDenominacaoActionPerformed(evt);
            }
        });

        tfQuantidadeEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQuantidadeEstoqueActionPerformed(evt);
            }
        });

        rbInativo.setText("Inativo");
        rbInativo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbInativoItemStateChanged(evt);
            }
        });
        rbInativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbInativoActionPerformed(evt);
            }
        });

        rbAtivo.setText("Ativo");
        rbAtivo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbAtivoItemStateChanged(evt);
            }
        });
        rbAtivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAtivoActionPerformed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Denominação", "Quantidade Estoque", "Preço", "Situação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnCadastrarItemStateChanged(evt);
            }
        });
        btnCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastrarMouseClicked(evt);
            }
        });
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnAlterarItemStateChanged(evt);
            }
        });
        btnAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlterarMouseClicked(evt);
            }
        });
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnExcluirItemStateChanged(evt);
            }
        });
        btnExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExcluirMouseClicked(evt);
            }
        });
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        painel2.setLayer(tfPreco, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painel2.setLayer(lbCodigo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painel2.setLayer(lbDenominacao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painel2.setLayer(lbQuantidadeEstoque, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painel2.setLayer(lbPreco, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painel2.setLayer(lbSituacao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painel2.setLayer(tfCodigo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painel2.setLayer(tfDenominacao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painel2.setLayer(tfQuantidadeEstoque, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painel2.setLayer(rbInativo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painel2.setLayer(rbAtivo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painel2.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painel2.setLayer(btnCadastrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painel2.setLayer(btnAlterar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painel2.setLayer(btnExcluir, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout painel2Layout = new javax.swing.GroupLayout(painel2);
        painel2.setLayout(painel2Layout);
        painel2Layout.setHorizontalGroup(
            painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel2Layout.createSequentialGroup()
                .addGroup(painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painel2Layout.createSequentialGroup()
                                .addComponent(lbCodigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painel2Layout.createSequentialGroup()
                                .addComponent(lbQuantidadeEstoque)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfQuantidadeEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painel2Layout.createSequentialGroup()
                                .addComponent(lbDenominacao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfDenominacao, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painel2Layout.createSequentialGroup()
                                .addComponent(lbSituacao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbAtivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbInativo))
                            .addGroup(painel2Layout.createSequentialGroup()
                                .addComponent(lbPreco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(painel2Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnAlterar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnExcluir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1116, Short.MAX_VALUE))
        );
        painel2Layout.setVerticalGroup(
            painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodigo)
                    .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDenominacao)
                    .addComponent(tfDenominacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQuantidadeEstoque)
                    .addComponent(tfQuantidadeEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPreco)
                    .addComponent(tfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSituacao)
                    .addComponent(rbAtivo)
                    .addComponent(rbInativo))
                .addGap(44, 44, 44)
                .addComponent(btnCadastrar)
                .addGap(18, 18, 18)
                .addComponent(btnAlterar)
                .addGap(18, 18, 18)
                .addComponent(btnExcluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirMouseClicked
        Connection con;
        try {
            con = ConexaoMysql.conexaoBanco();
            String sql = "DELETE FROM produto WHERE id_produto = ?";
            PreparedStatement stmt = con.prepareStatement(sql);
            stmt.setString(1, tfCodigo.getText());
            stmt.execute();
            JOptionPane.showMessageDialog(null, "Produto deletado!");
            stmt.close();
            con.close();
            atualizarTabela();
            resetarDados();
            
        } catch (SQLException ex) {
            Logger.getLogger(TelaExibicao.class.getName()).log(Level.SEVERE, null, ex);
            
        }
    }//GEN-LAST:event_btnExcluirMouseClicked

    private void btnExcluirItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnExcluirItemStateChanged

    }//GEN-LAST:event_btnExcluirItemStateChanged

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed

    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnAlterarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnAlterarItemStateChanged
        
    }//GEN-LAST:event_btnAlterarItemStateChanged

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed

    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarMouseClicked
        try {
            Connection con = ConexaoMysql.conexaoBanco();
            String sql = "INSERT INTO produto(denominacao, quantidade_estoque, preco, situacao)"
            + "VALUES(?,?,?,?);";
            PreparedStatement stmt = con.prepareStatement(sql);
            stmt.setString(1, tfDenominacao.getText());
            stmt.setString(2, tfQuantidadeEstoque.getText());
            stmt.setString(3, tfPreco.getText());
            stmt.setString(4, situacao);
            stmt.execute();
            JOptionPane.showMessageDialog(null, "Cadastro efetuado com sucesso!!!");
            stmt.close();
            con.close();
            atualizarTabela();
            resetarDados();

        } catch (SQLException ex) {
            Logger.getLogger(TelaExibicao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCadastrarMouseClicked

    private void btnCadastrarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnCadastrarItemStateChanged

    }//GEN-LAST:event_btnCadastrarItemStateChanged

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        tfCodigo.setText(tabela.getValueAt(tabela.getSelectedRow(), 0).toString());
        tfDenominacao.setText(tabela.getValueAt(tabela.getSelectedRow(), 1).toString());
        tfQuantidadeEstoque.setText(tabela.getValueAt(tabela.getSelectedRow(), 2).toString());
        tfPreco.setText(tabela.getValueAt(tabela.getSelectedRow(), 3).toString());
        situacao = tabela.getValueAt(tabela.getSelectedRow(), 4).toString();
        
        if (situacao.equals("A")) {
            rbAtivo.setSelected(true);

        } else if (situacao.equals("I")) {
            rbInativo.setSelected(true);

        }
    }//GEN-LAST:event_tabelaMouseClicked

    private void rbAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAtivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbAtivoActionPerformed

    private void rbAtivoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbAtivoItemStateChanged
        situacao = "A";

        if (rbAtivo.isSelected()) {
            rbInativo.setSelected(false);
        }
    }//GEN-LAST:event_rbAtivoItemStateChanged

    private void rbInativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbInativoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbInativoActionPerformed

    private void rbInativoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbInativoItemStateChanged
        situacao = "I";

        if (rbInativo.isSelected()) {
            rbAtivo.setSelected(false);
        }
    }//GEN-LAST:event_rbInativoItemStateChanged

    private void tfQuantidadeEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQuantidadeEstoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQuantidadeEstoqueActionPerformed

    private void tfDenominacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDenominacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDenominacaoActionPerformed

    private void tfCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCodigoActionPerformed

    private void tfPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPrecoActionPerformed

    private void btnAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarMouseClicked
        try {
            Connection con = ConexaoMysql.conexaoBanco();
            String sql = "UPDATE produto SET denominacao = ?, quantidade_estoque = ?, preco = ?, situacao = ? WHERE id_produto = ?; ";
            PreparedStatement stmt = con.prepareStatement(sql);
            stmt.setString(1, tfDenominacao.getText());
            stmt.setString(2, tfQuantidadeEstoque.getText());
            stmt.setString(3, tfPreco.getText());
            stmt.setString(4, situacao);
            stmt.setString(5, tfCodigo.getText());
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Dados do produto atualizados!");
            stmt.close();
            con.close();
            atualizarTabela();
            resetarDados();

        } catch (SQLException ex) {
            Logger.getLogger(TelaExibicao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAlterarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbDenominacao;
    private javax.swing.JLabel lbPreco;
    private javax.swing.JLabel lbQuantidadeEstoque;
    private javax.swing.JLabel lbSituacao;
    private javax.swing.JDesktopPane painel2;
    private javax.swing.JRadioButton rbAtivo;
    private javax.swing.JRadioButton rbInativo;
    private javax.swing.ButtonGroup rbSituacao;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfDenominacao;
    private javax.swing.JTextField tfPreco;
    private javax.swing.JTextField tfQuantidadeEstoque;
    // End of variables declaration//GEN-END:variables
}
