/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package aula10exercícioreplicarexemploanterior;

    import java.text.SimpleDateFormat;
    import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rafael55957146
 */
public class TelaCadastro extends javax.swing.JInternalFrame {

    String genero;//RadioButton Feminino ou Masculino
    String ocupacaoEstudante = "";//CheckBox
    String ocupacaoEstagiario = "";//CheckBox
    String situacao;//RadioButton

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbSituacao = new javax.swing.ButtonGroup();
        rbGenero = new javax.swing.ButtonGroup();
        painel = new javax.swing.JDesktopPane();
        RbAtivo = new javax.swing.JRadioButton();
        nome = new javax.swing.JTextField();
        RbInativo = new javax.swing.JRadioButton();
        BCadastrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        chEstudante = new javax.swing.JCheckBox();
        rbFeminino = new javax.swing.JRadioButton();
        rbMasculino = new javax.swing.JRadioButton();
        chEstagiario = new javax.swing.JCheckBox();
        dataNascimento = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        RbAtivo.setText("Ativo");
        RbAtivo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                RbAtivoItemStateChanged(evt);
            }
        });

        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });

        RbInativo.setText("Inativo");
        RbInativo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                RbInativoItemStateChanged(evt);
            }
        });

        BCadastrar.setText("Cadastrar");
        BCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BCadastrarMouseClicked(evt);
            }
        });
        BCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCadastrarActionPerformed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Data Nascimento", "Genero", "Ocupações", "Situação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela);

        jLabel1.setText("Nome:");

        jLabel2.setText("Data de Nascimento");

        chEstudante.setText("Estudante");
        chEstudante.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chEstudanteItemStateChanged(evt);
            }
        });
        chEstudante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chEstudanteActionPerformed(evt);
            }
        });

        rbFeminino.setText("Feminino");
        rbFeminino.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbFemininoItemStateChanged(evt);
            }
        });
        rbFeminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFemininoActionPerformed(evt);
            }
        });

        rbMasculino.setText("Masculino");
        rbMasculino.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbMasculinoItemStateChanged(evt);
            }
        });
        rbMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMasculinoActionPerformed(evt);
            }
        });

        chEstagiario.setText("Estagiário");
        chEstagiario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chEstagiarioItemStateChanged(evt);
            }
        });

        painel.setLayer(RbAtivo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painel.setLayer(nome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painel.setLayer(RbInativo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painel.setLayer(BCadastrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painel.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painel.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painel.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painel.setLayer(chEstudante, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painel.setLayer(rbFeminino, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painel.setLayer(rbMasculino, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painel.setLayer(chEstagiario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painel.setLayer(dataNascimento, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout painelLayout = new javax.swing.GroupLayout(painel);
        painel.setLayout(painelLayout);
        painelLayout.setHorizontalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLayout.createSequentialGroup()
                .addContainerGap(562, Short.MAX_VALUE)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelLayout.createSequentialGroup()
                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rbFeminino)
                            .addComponent(rbMasculino))
                        .addGap(18, 18, 18)
                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BCadastrar)
                            .addGroup(painelLayout.createSequentialGroup()
                                .addComponent(chEstagiario)
                                .addGap(19, 19, 19)
                                .addComponent(RbInativo))
                            .addGroup(painelLayout.createSequentialGroup()
                                .addComponent(chEstudante)
                                .addGap(18, 18, 18)
                                .addComponent(RbAtivo)))))
                .addGap(543, 543, 543))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        painelLayout.setVerticalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(dataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbFeminino)
                    .addComponent(chEstudante)
                    .addComponent(RbAtivo))
                .addGap(18, 18, 18)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbMasculino)
                    .addComponent(chEstagiario)
                    .addComponent(RbInativo))
                .addGap(18, 18, 18)
                .addComponent(BCadastrar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void BCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BCadastrarActionPerformed

    private void BCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BCadastrarMouseClicked
    // Adicionando uma formatação a data
    SimpleDateFormat dataFormatada = new SimpleDateFormat("dd/MM/yyyy");
    
    // Adicionando uma variavel formatada da data de nascimento
    String data = dataFormatada.format(dataNascimento.getDate());
    
    //Pegando a tabela e adcionando dados a cada linha
    DefaultTableModel tabelaDados = (DefaultTableModel) tabela.getModel();
    Object[] dados ={nome.getText(),data,genero,ocupacaoEstagiario
    +" "+ocupacaoEstudante,situacao};
    tabelaDados.addRow(dados);//Colocar os dados dentro da tabela

    //Limpar todos os campos:
    rbSituacao.clearSelection();
    rbGenero.clearSelection();
    chEstagiario.setSelected(false);
    chEstudante.setSelected(false);
    nome.setText(null);
    dataNascimento.setDate(null);
    }//GEN-LAST:event_BCadastrarMouseClicked

    private void rbFemininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFemininoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFemininoActionPerformed

    private void rbFemininoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbFemininoItemStateChanged
        genero = "Feminino";//Definir o Genero do RadioButton
    }//GEN-LAST:event_rbFemininoItemStateChanged

    private void rbMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMasculinoActionPerformed
        
    }//GEN-LAST:event_rbMasculinoActionPerformed

    private void chEstudanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chEstudanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chEstudanteActionPerformed

    private void chEstudanteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chEstudanteItemStateChanged
       //Se o CheckBox estiver marcado, vai alterar para Estudante,se não vai trazer vazio
        if(chEstudante.isSelected()==true){
        ocupacaoEstudante = "Estudante";
        } else {
        ocupacaoEstudante = "";
        }
    }//GEN-LAST:event_chEstudanteItemStateChanged

    private void chEstagiarioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chEstagiarioItemStateChanged
        if(chEstagiario.isSelected()==true){
        ocupacaoEstagiario = "Estagiario";
        } else {
        ocupacaoEstagiario = "";
        }       
    }//GEN-LAST:event_chEstagiarioItemStateChanged

    private void RbAtivoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_RbAtivoItemStateChanged
        situacao = "Ativo";//Definir a Situação do RadioButton para Ativo
    }//GEN-LAST:event_RbAtivoItemStateChanged

    private void RbInativoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_RbInativoItemStateChanged
        situacao = "Inativo";//Definir a Situação do RadioButton para Inativo
    }//GEN-LAST:event_RbInativoItemStateChanged

    private void rbMasculinoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbMasculinoItemStateChanged
        genero = "Masculino";//Definir o Genero do RadioButton
    }//GEN-LAST:event_rbMasculinoItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCadastrar;
    private javax.swing.JRadioButton RbAtivo;
    private javax.swing.JRadioButton RbInativo;
    private javax.swing.JCheckBox chEstagiario;
    private javax.swing.JCheckBox chEstudante;
    private com.toedter.calendar.JDateChooser dataNascimento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nome;
    private javax.swing.JDesktopPane painel;
    private javax.swing.JRadioButton rbFeminino;
    private javax.swing.ButtonGroup rbGenero;
    private javax.swing.JRadioButton rbMasculino;
    private javax.swing.ButtonGroup rbSituacao;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
