/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aula4logica.aeronave;

import javax.swing.JOptionPane;

/**
 *
 * @author Rafael55957146
 */
public class Tela extends javax.swing.JFrame {

    // Variavel do acumulador
    int acumulador = 0;
    
    
    public Tela() {
        initComponents();
        
        
        // Destivando TextField de inicio
        check.setEnabled(false);
        ligarDesligar.setEnabled(false);
        subir.setEnabled(false);
        descer.setEnabled(false);
        decolagem.setEnabled(false);
        pouso.setEnabled(false);
        
        
        // Colocando textos iniciais no TextField
        check.setText("Não feito");
        ligarDesligar.setText("Desligado");
        subir.setText(acumulador+ " mil pés");
        descer.setText(acumulador+ " mil pés");
        decolagem.setText("Não Autorizado");
        pouso.setText("Não feito");
        
        
    }
    
    public void atualizarResultado() {
    
    //resultado que vai ser exibido
    resultado.setText(
                "CheckList: " +check.getText()+ "\n"

                +"Aeronave: " +ligarDesligar.getText()+ "\n"
                +"Altitude: " +acumulador+ " mil pés"+ "\n"
                
                +"Autorizar Decolagem: " +decolagem.getText()+ "\n"
                +"Altorizar Pouso: " +pouso.getText()+ "\n"
                
                );

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLigarDesligar = new javax.swing.JButton();
        btnPouso = new javax.swing.JButton();
        btnCheck = new javax.swing.JButton();
        btnSubir = new javax.swing.JButton();
        ligarDesligar = new javax.swing.JTextField();
        descer = new javax.swing.JTextField();
        check = new javax.swing.JTextField();
        decolagem = new javax.swing.JTextField();
        pouso = new javax.swing.JTextField();
        btnDecolagem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultado = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btnDescer = new javax.swing.JButton();
        subir = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLigarDesligar.setText("Ligar/Desligar Aeronave");
        btnLigarDesligar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLigarDesligarActionPerformed(evt);
            }
        });

        btnPouso.setText("Autorizar Pouso");
        btnPouso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPousoActionPerformed(evt);
            }
        });

        btnCheck.setText("Fazer Checklist");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        btnSubir.setText("Subir aeronave");
        btnSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubirActionPerformed(evt);
            }
        });

        ligarDesligar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ligarDesligarActionPerformed(evt);
            }
        });

        descer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descerActionPerformed(evt);
            }
        });

        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });

        decolagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decolagemActionPerformed(evt);
            }
        });

        pouso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pousoActionPerformed(evt);
            }
        });

        btnDecolagem.setText("Decolagem");
        btnDecolagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecolagemActionPerformed(evt);
            }
        });

        resultado.setColumns(20);
        resultado.setRows(5);
        jScrollPane1.setViewportView(resultado);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Comandos da Aeronave");

        btnDescer.setText("Descer aeronave");
        btnDescer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescerActionPerformed(evt);
            }
        });

        subir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnPouso, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pouso, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDecolagem, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(decolagem, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLigarDesligar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSubir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDescer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(check, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ligarDesligar, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                .addComponent(descer)
                                .addComponent(subir))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCheck)
                    .addComponent(check, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ligarDesligar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLigarDesligar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubir)
                    .addComponent(subir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDescer)
                    .addComponent(descer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDecolagem)
                    .addComponent(decolagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPouso)
                    .addComponent(pouso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void descerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descerActionPerformed
        acumulador = acumulador - 10;
        descer.setText(acumulador+ " mil pés");

    }//GEN-LAST:event_descerActionPerformed

    private void pousoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pousoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pousoActionPerformed

    private void decolagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decolagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_decolagemActionPerformed

    private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed

    }//GEN-LAST:event_checkActionPerformed

    private void btnLigarDesligarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLigarDesligarActionPerformed
       if (ligarDesligar.getText().equals("Desligado")) {
           ligarDesligar.setText("Ligado");
           atualizarResultado();
       } else {
           ligarDesligar.setText("Desligado");
           decolagem.setText("Não autorizado");
           acumulador = acumulador - acumulador;
           subir.setText(acumulador+ " mil pés");
           descer.setText(acumulador+ " mil pés");
           atualizarResultado();
       };
    }//GEN-LAST:event_btnLigarDesligarActionPerformed

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        if (ligarDesligar.getText().equals("Desligado")) {
           JOptionPane.showMessageDialog(null, "Ligue a aeronave!!");
           check.setText("Não feito");
           atualizarResultado();
       } else {
           check.setText("Aeronave funcionando");
           atualizarResultado();        
       };
    }//GEN-LAST:event_btnCheckActionPerformed

    private void btnSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubirActionPerformed
       
        if (ligarDesligar.getText().equals("Desligado")) {
            JOptionPane.showMessageDialog(null, "Ligue a aeronave!!");
            atualizarResultado();    
        } else if (decolagem.getText().equals("Não Autorizado")) {
            JOptionPane.showMessageDialog(null, "Você precisa de autorização!");
            atualizarResultado(); 
        } else {
            acumulador = acumulador + 10;
            subir.setText(acumulador+ " mil pés");
            descer.setText(acumulador+ " mil pés");
            atualizarResultado();
       }
        
        
    }//GEN-LAST:event_btnSubirActionPerformed

    private void btnDescerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescerActionPerformed
        
        if (ligarDesligar.getText().equals("Desligado")) {
            JOptionPane.showMessageDialog(null, "Ligue a aeronave!!");
            atualizarResultado();
        } else if (pouso.getText().equals("Autorizado") && acumulador >= 0) {
            acumulador = acumulador - 10;
            subir.setText(acumulador+ " mil pés");
            descer.setText(acumulador+ " mil pés");
            atualizarResultado();
        } 

    }//GEN-LAST:event_btnDescerActionPerformed

    private void subirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subirActionPerformed

    private void ligarDesligarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ligarDesligarActionPerformed
        if (ligarDesligar.getText().equals("Desligado")) {
            ligarDesligar.setText("Ligado");
            atualizarResultado();
        } else {
            ligarDesligar.setText("Desligado");
        }
    }//GEN-LAST:event_ligarDesligarActionPerformed

    private void btnDecolagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecolagemActionPerformed
        if (ligarDesligar.getText().equals("Desligado") ) {
           JOptionPane.showMessageDialog(null, "Ligue a aeronave!!");
        } else {
           decolagem.setText("Autorizado");
           atualizarResultado();
        }
    }//GEN-LAST:event_btnDecolagemActionPerformed

    private void btnPousoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPousoActionPerformed
        if (acumulador > 0) {
            pouso.setText("Autorizado");
        } else  {
            JOptionPane.showMessageDialog(null, "Você precisa estar voando!");
        }
    }//GEN-LAST:event_btnPousoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnDecolagem;
    private javax.swing.JButton btnDescer;
    private javax.swing.JButton btnLigarDesligar;
    private javax.swing.JButton btnPouso;
    private javax.swing.JButton btnSubir;
    private javax.swing.JTextField check;
    private javax.swing.JTextField decolagem;
    private javax.swing.JTextField descer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField ligarDesligar;
    private javax.swing.JTextField pouso;
    private javax.swing.JTextArea resultado;
    private javax.swing.JTextField subir;
    // End of variables declaration//GEN-END:variables
}
